### PR TITLE
Updates for ICAPS developments.

### PR DESCRIPTION
**Pull request by arbimo**
The quick and dirty changes I made for the benchmark of the ICAPS paper are in a separate "icaps-expe" branch. It should not be merged as is.
We should cherry pick the changes we want, and fix the bugs that required a work around.

New features:
 - planning stops based on a maximum time insead of maximum iterations
 - shuffler can be configured with JSON
 - shuffler uses iteration number to decide whether to shuffle or not.
 - many more different VNS configurations
 - improvement in benchmarking scripts

Things that should be fixed before merging:
 - I was not able to use the external configuration file for defining neighborhoods. benchmark.py still used the ones defined in locally. As a result all new neighborhood in this branch were added to "benchmark.py" directly
 - benchmarking scripts need o be cleaned up to make sure they run on something else than my machine.
 - I added a flag to make the VNS search silent, but it is not configurable at runtime

### CODE REVIEW

**Comment by rafael1193** [comment]
- I think changes that affect to scripts/benchmarking/analyze.py can be cherry-picked "as-they-are".
- Why you weren't able to use the external VNS confs?
- There should be a way to connect std::cout to the python logger, so we could configure its "verbosity". A possible clue: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html#capturing-standard-output-from-ostream combined with this https://stackoverflow.com/questions/11124093/redirect-python-print-output-to-logger#11124247

**Comment by arbimo** [comment]
> Why you weren't able to use the external VNS confs?

When updating the configuration in the external file, the changes where not picked-up. Instead, the benchmark script was still using the configurations defined in `benchmark.py`. Removing them from `benchmark.py` resulted in hte configurations no being found.
Let me know if you can reproduce this, otherwise I might have messed up with the command line options.

**Comment by arbimo** [comment]
Also it seems like the `--parallel` option makes a bad usage of CPU.
Not very scientific tests: simply looking up CPU usage with `htop`, the CPU usage really does not scale with the number of threads. Its probably fine for development, but not to actually produce results for papers or deep analysis.

Instead running N times `benchmark.py` would result in N CPUs being consistently used at a 100%.
That's what I used to produce the results for the paper. I have the updated `run.sh` script on another machine, I'll try to add it.

**Comment by rafael1193** [comment]
wrt the external VNS confs I think I discovered the issue. As ```vns_configurations``` dictionary is a global variable, when it should be getting replaced by ```vars(args.vns_conf)``` it is in fact being assigned to a new ```vns_configurations``` that shadows the global definition. This is a --let's say particular-- python behavior.  run_benchmark gets only the name of the conf and access the unchanged global  ```vns_configurations``` instead of the new one. 

It is easier to get it fixed than explained. It is ok now in #13

**Comment by rafael1193** [comment]
wrt to ```--parallel```, I'm a bit disappointed but not surprised. cPython **can not** run multiple threads at the same time because of the _Global Interpreter Lock_. But, as most of our planning is done in the C++ library we can release the GIL when calling ```plan_vns```. I hopped ```joblib``` was correctly using the ```multiprocessing``` module to parallelize the python part but apparently not... 😞

**Pull request closed without merging**
