### PR TITLE
Configure travis-ci to automatically run tests after each commit

### PR DESCRIPTION
**Pull request by rafael1193**
Basic configuration to use Travis CI.

This is only an initial work. Travis doesn't support Ubuntu 16.04 (xenial) yet, so python 3.5 is not available but required the project.

Possible workarounds are:
- Change the project language to python so the build is in a python virtualenv
- Use the docker container in the travis build (https://docs.travis-ci.com/user/docker/)

### CODE REVIEW

**Comment by rafael1193** [comment]
Changing the project language to python in a 3.5 virtualenv helps going forward into the building process. However it gets stuck while installing the GDAL python bindings.

**Comment by arbimo** [comment]
I'll try to setup the test environment using the existing Dockerfile (as it already contains all necessary installation steps). One thing we will be missing though is the elevation data, so in fact Travis might not be a perfect fit :/
I suppose we are not allowed to make elevation data available (even hidden somewhere in a container) ?

**Comment by rafael1193** [comment]
Maybe, the elevation data could be stored in a git repository that is checkout every time the test runs. But, as our travis configuration is public, anyone would be able to retrieve the information then...

**Comment by arbimo** [comment]
I have made a new travis configuration that uses docker behind the scene.
It still incomplete: it only checks that the code compile and can run benchmark.py without crashing. However, other tests should be easy to add.

It is merged in master with build passing, hence I am closing this one.

**Pull request closed without merging**
